### ISSUE TITLE
support recursion in PersistingRdfStreamConsumer

### ISSUE THREAD

**Issue by christopher-johnson** [fcrepo4/fcrepo4#1045]
I have a N3 graph that looks like this.
```turtle
<http://localhost:8080/fcrepo/rest/object/id:0001> <p1> <o1> ;  ...  ; <p30> <o30>  .
<http://localhost:8080/fcrepo/rest/object/id:0002> <p1> <o1> ;  ...  ; <p30> <o30>  .
```
and so on for many thousands of ids.  I would like to just run a command like this:

```bash
$> curl -X PUT -H "Content-Type: application/n-triples" -H"Prefer: handling=lenient; received="minimal"" --data-binary "@update_rdf.n3" "http://localhost:8080/fcrepo/rest/object"
```  
and have the consumer understand that the subjects are just children of the topic.  AFAIK, this is not yet supported and the only way to do this is to create separate data-binary import files for each subject and then point the target command at each child.   (If there is an existing method I am missing, please let me know!)

The motivation for this is in line with [LDP UC4: Update existing resource](https://dvcs.w3.org/hg/ldpwg/raw-file/default/ldp-ucr.html#dfn-f4.2).  

The workflow is index the Fedora data into Fuseki, do a selective SPARQL UPDATE, construct and reserialize the graph as N3, and replace the parent container in Fedora.

**Comment by escowles** [comment]
One option that would allow the kind of behavior you describe would be to use hash URIs for the subjects and objects, e.g.:

```
<http://localhost:8080/fcrepo/rest/object#s01> <p1> <#o1> ;  ...  ; <p30> <#o30>  .
<http://localhost:8080/fcrepo/rest/object#s02> <p1> <#o1> ;  ...  ; <p30> <#o30>  .
```

This would effectively bundle all of the resources under a single Fedora object and allow updating them by POSTing a single RDF description, or doing a single SPARQL Update.

Another option you could explore would be implementing some kind of batch operations.  There was a discussion at LDCX in March that might be related to this: discussing the possibility of implementing a batch mode where you could post many RDF documents bundled together in a single request: https://ldcx2016.sched.org/event/6Wrj/4c-ldp-batch  -- and there is also a Fedora ticket for this work: https://jira.duraspace.org/browse/FCREPO-1963

I got as far as investigating how this could be implemented and decided that you would need to manually parse the incoming requests (as opposed to just unwrapping them and handing them off to JAX-RS) and [mocking that up](https://github.com/escowles/fcrepo-batch).

There was little support for implementing batch operations in the Fedora core code because of the expectation that HTTP/2 would soon make it more efficient to pipeline hundreds or thousands of separate requests.

**Comment by ajs6f** [comment]
Guys, let's take this to Jira right away. I've created a [ticket](https://jira.duraspace.org/browse/FCREPO-2042) for the purpose.

**Comment by ajs6f** [comment]
I've left further comments at that ticket.

**Comment by awoods** [comment]
Tracking on JIRA: https://jira.duraspace.org/browse/FCREPO-2042

**Comment by christopher-johnson** [comment]
Thank you for looking in to this. 
@escowles the hash option is viable for some of my objects and I had not considered that at all in the URI design.  I have tested it with data.  I was initially concerned that the UI would be slow, but even with 5000+ objects, it works fine, and I like how it renders the label as well.  However, I do not think that the single container will be an option for the batch updates of fcr:metadata, as the curl command would still look like this:
```bash
$> curl -X PUT -H "Content-Type: application/n-triples" -H"Prefer: handling=lenient; received="minimal"" --data-binary "@update_rdf.n3" "http://localhost:8080/fcrepo/rest/res#0092.tif/fcr:metadata"
```

@ajs6f, I will comment here as I do not have a JIRA account.  My use case is driven by practical management costs rather than performance needs.  I am comfortable with manipulating graphs with SPARQL.  For example, adding or changing a property for an entire graph based arbitrary criteria is quite simple.  So my flow is driven by administration first.  For example, I build the dataset with bulk construct updates, like modifying the svcs:has_service base URI in fcr:metadata (from the IIIF Presentation API).  It is possible of course to create a script that does this on a "one off" basis in fcrepo, though it is much easier to do in the triplestore.  

It seems to me that some kind of "topic to child subject inheritance" could be part of the consumer API.  The parent topic can simply deliver the request to its children if it knows that the subject is within its scope.  Similar to a transitive property path algorithm, I guess. I do not know anything about the mechanics of the update process of the consumer, however.  I hope that this helps!

Cheers,
Christopher
