### ISSUE TITLE
MOVE - Cannot delete Solr index

### ISSUE THREAD

**Issue by gedhi** [fcrepo4/fcrepo4#1276]
Hi,

i've found this bug. When i MOVE a content from URI to other URI the original Solr index still remain indexed.

`curl -u fedoraAdmin:secret3 -X MOVE -H "Destination: http://172.17.0.2:8080/fcrepo/rest/TRX_OFFLINE/TEST_00000000030" "http://172.17.0.2:8080/fcrepo/rest/TRX/TEST_00000000030"`

This command generate a delete request on Solr, by karaf, but with an invalid ID
_karaf.log_

`2018-01-11 22:48:40,767 | INFO  | Consumer[fedora] | SolrRouter                       | 245 - org.fcrepo.camel.fcrepo-indexing-solr - 4.7.2 | Deleting Solr Object info:fedora/TRX/TEST_00000000041`

why just in MOVE command Fedora prepend a **_info:fedora_** into uri?

Ovviusly in Solr nothing are found (for delete):

_solr.log_

`INFO  - 2018-01-11 22:48:40.769; org.apache.solr.update.processor.LogUpdateProcessor; [collection1] webapp=/solr path=/update params={commitWithin=10000} {delete=[info:fedora/TRX/TEST_00000000041 (-1589338094456274944)]} 0 0`

The add in Solr works (same MOVE call)

_karaf.log_

`2018-01-11 22:48:40,771 | INFO  | Consumer[fedora] | SolrRouter                       | 245 - org.fcrepo.camel.fcrepo-indexing-solr - 4.7.2 | Indexing Solr Object http://172.17.0.2:8080/fcrepo/rest/TRX_OFFLINE/TEST_00000000041`

_solr.log_

`INFO  - 2018-01-11 22:48:40.869; org.apache.solr.update.processor.LogUpdateProcessor; [collection1] webapp=/solr path=/update params={commitWithin=10000} {add=[http://172.17.0.2:8080/fcrepo/rest/TRX_OFFLINE/TEST_00000000041 (1589338094557986816)]} 0 3`

Anyone can help me?
It's a BUG?
The DELETE works, same for PUT.

Thanks and regards,

Attached file:
[karaf.log](https://github.com/fcrepo4/fcrepo4/files/1633034/karaf.log)
[solr.log](https://github.com/fcrepo4/fcrepo4/files/1633037/solr.log)

**Ubuntu 14.04 64-bit machine with:**
_Fedora Webapp Plus 4.7.4
Fcrepo-camel-toolbox 4.7.2
Solr 4.10.3_

**Comment by DiegoPino** [comment]
Hi @gedhi, I think issues are being handled on JIRA (https://jira.duraspace.org/projects/FCREPO/issues/FCREPO-2582?filter=allopenissues)

I have not been very active on this project lately and there are other people a lot more knowledgable of the source code here, but the Camel indexers doing in this is pretty simple, look at this:

https://github.com/fcrepo4-exts/fcrepo-camel-toolbox/blob/master/fcrepo-indexing-solr/src/main/java/org/fcrepo/camel/indexing/solr/SolrRouter.java

It deals with updates (index) or deletes based on the message/event it gets and has no knowledge of the specifities of the content/paths, etc. So nothing wrong there or prone to fail to my old eyes.

But: looking at fcrepo code (i did a general search on the source using the word "MOVE", silly approach) probably this piece here has something to do with it and worth debugging or following deeper.

https://github.com/fcrepo4/fcrepo4/blob/6034a73c0b3acca0622362b3c06dd48169b4a535/fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/SimpleObserver.java#L109-L115

In specific the way the event is constructed https://github.com/fcrepo4/fcrepo4/blob/6034a73c0b3acca0622362b3c06dd48169b4a535/fcrepo-kernel-modeshape/src/main/java/org/fcrepo/kernel/modeshape/observer/SimpleObserver.java#L128-L131, it could be also in the  movePath = evt.getInfo() (meaning in the geInfo method)? So basically start tracing back from there...

So what i would do: on the camel side of things, (because it is easier to debug/modify) add some Event dumper and see what is in there first, then trace the origin of the wrong URI/IRI for the delete component of the move to its source. Also, i suggest opening a JIRA issue to get better and more answers. Hope any of this helps. Cheers

**Comment by awoods** [comment]
Thanks @DiegoPino !

**Comment by gedhi** [comment]
Thanks @DiegoPino ,
you make exactly the same mine problem determination :-)
But on the jira platform i don't have an account.
I requested one! ;-)

**Comment by gedhi** [comment]
https://jira.duraspace.org/browse/FCREPO-2663
