### ISSUE TITLE
Fixity checking on federated filesystems not working? 

### ISSUE THREAD

**Issue by cmstokoe** [fcrepo4/fcrepo4#777]
I've integrated an externalSource into my repository using the following configuration

 "externalSources" : {
          "federated-directory" : {
                 "classname" : "org.fcrepo.connector.file.FedoraFileSystemConnector",
                 "directoryPath" : "/tmp/repo",
                 "propertiesDirectoryPath" : "/tmp/",
                 "projections" : [ "default:/test => /" ],
                 "contentBasedSha1" : "true",
                 "readOnly" : false,
                 "extraPropertiesStorage" : "store",
                 "cacheTtlSeconds" : 5
           }
    },

I can see the files contained there but performing a fixity check returns the current sha1 as opposed to the sha1 on initial access?

**Comment by escowles** [comment]
Yes, it looks like it's using the current sha1 instead of the value cached in the external properties store, which is probably not what we want to do.  If content-based sha1 isn't enabled, it's even worse, since it compares the content sha1 to the filename checksum, which would fail unless the content happened to be the same as the filename.

We should revisit the how the federation interacts with the fixity service.  Does it make sense to perform fixity checks?  Do we always use the stored checksum, or do we sometimes update it?  How do we know when an update was a file being intentionally changed, as opposed to corruption?  It may be better to disable the fixity service for federated content, or require including the sha1 to compare against in the request.

We are also reconsidering the fixity service design as a whole, in particular considering changing GET requests to only report the last fixity check and requiring a POST to do a new check, which would be saved as a node.

**Comment by TheStokoe** [comment]
The documentation currently described federated filesystems behaving like a read only filesystem with a fixity based on initial compute of a sha1 (generated on first access)... I've just issued Pull Request #778 that makes it behave in a way that's consistent with the current documentation. 

If it counts for anything the functionality to fixity check a remote / external filesystem was a key factor in us looking to adopt Fedora ....

**Comment by escowles** [comment]
Doing some testing locally, I think the federated filesystem already uses the stored checksum for doing the fixity check, unless the file has been modified since the properties were stored.  If I modify a file and do a fixity check, it will recalculate the checksum and the fixity check will succeed.  If I modify a file and then modify the timestamp to before the properties were saved, then the fixity check will use the saved checksum and fail.

Do you have a use case for wanting to use the cached checksum even though the file has changed?  Are you trying to detect changes made on the remote system?

**Comment by TheStokoe** [comment]
yes essentially.... Any change on the remote is indicative of data corruption in the context of my use case. 

I guess my reading of https://wiki.duraspace.org/plugins/servlet/mobile#content/view/60948524 Is that on first access a sha1 is computed for the remote file and any deviation from that should result in a bad checksum.... perhaps that is too simplistic a reading?

**Comment by escowles** [comment]
I don't think everybody would want any change to be reported as a fixity error.  Could you just check whether the fedora:created and fedora:lastModified dates are the same to see if the file has been modified since it was first seen?  That seems like a better fit to me than expecting the federation to ignore the file being modified outside of fcrepo in some circumstances.

**Comment by acoburn** [comment]
I am closing this issue as the support for federated filesystems has been moved out of the core of Fedora. @ghost you may wish to take up this issue with whoever takes on the maintenance of the new [fcrepo-connector-file](https://github.com/fcrepo4-exts/fcrepo-connector-file) repository.
