### ISSUE TITLE
I think Prefer InboundRefernces is going too deep.

### ISSUE THREAD

**Issue by jcoyne** [fcrepo4/fcrepo4#884]
I did this:
```
curl -H "Accept: text/turtle" -H "Prefer: return=representation; include=\"http://fedora.info/definitions/v4/repository#InboundReferences\"" http://127.0.0.1:8080/fedora/rest/prod/f3/xp/73/2v/f3xp732v > out.ttl
```

and got this file:  https://gist.github.com/jcoyne/5d153463e1379ac2324b

Should triples like this be in that response?
```
<http://127.0.0.1:8080/fedora/rest/prod/f3/rv/0k/sk/f3rv0ksk> <http://pcdm.org/models#hasMember> <http://127.0.0.1:8080/fedora/rest/prod/0b/a2/dc/77/0ba2dc77-bb4f-4b74-aaf9-17d64a369be2> .
```

**Comment by jcoyne** [comment]
This request also goes pretty slow. I'm seeing 800ms-1100ms.

**Comment by awoods** [comment]
@jcoyne, which version of F4 is this?

**Comment by escowles** [comment]
I suspect the issue here is the recent update to add inbound references that are generated by IndirectContainers (https://github.com/fcrepo4/fcrepo4/commit/8845a22fdeffbec07bb0d0abd35ec9fd3854e788).  There may need to be some more logic to make sure the inbound references are from the source node to prevent this from happening.

**Comment by jcoyne** [comment]
@awoods 4.3.0

**Comment by awoods** [comment]
Tracking here: https://jira.duraspace.org/browse/FCREPO-1701

**Comment by acoburn** [comment]
This issue was addressed some time ago via https://github.com/fcrepo4/fcrepo4/commit/731e92ca5ad30e83edae4ef6db972d9e8a1e72fd
